# server.port=8079
# #Sserver.port=8091
# #connexion sur eureka
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# #decouverte dynamique des routes
# spring.cloud.gateway.discovery.locator.enabled=true

# spring.cloud.gateway.discovery.locator.lower-case-service-name=true


# # Activation et configuration globale du CORS pour la Gateway
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders[0]=*

server.port=8079
# connexion sur eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# decouverte dynamique des routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-name=true

# Activation et configuration globale du CORS pour la Gateway
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders[0]=*
# Permettre l'échange de cookies ou d'en-têtes d'authentification si nécessaire
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# 🔥 LA LIGNE MAGIQUE POUR SUPPRIMER LES DOUBLONS CORS 🔥
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST